// Generated by gencpp from file motorcycle_gz/input.msg
// DO NOT EDIT!


#ifndef MOTORCYCLE_GZ_MESSAGE_INPUT_H
#define MOTORCYCLE_GZ_MESSAGE_INPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motorcycle_gz
{
template <class ContainerAllocator>
struct input_
{
  typedef input_<ContainerAllocator> Type;

  input_()
    : force(0.0)
    , v(0.0)
    , d(0.0)
    , t(0.0)  {
    }
  input_(const ContainerAllocator& _alloc)
    : force(0.0)
    , v(0.0)
    , d(0.0)
    , t(0.0)  {
  (void)_alloc;
    }



   typedef double _force_type;
  _force_type force;

   typedef double _v_type;
  _v_type v;

   typedef double _d_type;
  _d_type d;

   typedef double _t_type;
  _t_type t;





  typedef boost::shared_ptr< ::motorcycle_gz::input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motorcycle_gz::input_<ContainerAllocator> const> ConstPtr;

}; // struct input_

typedef ::motorcycle_gz::input_<std::allocator<void> > input;

typedef boost::shared_ptr< ::motorcycle_gz::input > inputPtr;
typedef boost::shared_ptr< ::motorcycle_gz::input const> inputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motorcycle_gz::input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motorcycle_gz::input_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motorcycle_gz::input_<ContainerAllocator1> & lhs, const ::motorcycle_gz::input_<ContainerAllocator2> & rhs)
{
  return lhs.force == rhs.force &&
    lhs.v == rhs.v &&
    lhs.d == rhs.d &&
    lhs.t == rhs.t;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motorcycle_gz::input_<ContainerAllocator1> & lhs, const ::motorcycle_gz::input_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motorcycle_gz

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::motorcycle_gz::input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motorcycle_gz::input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motorcycle_gz::input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motorcycle_gz::input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motorcycle_gz::input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motorcycle_gz::input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motorcycle_gz::input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ccb91360ba5aa0292ae5dfbab053fc4";
  }

  static const char* value(const ::motorcycle_gz::input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ccb91360ba5aa02ULL;
  static const uint64_t static_value2 = 0x92ae5dfbab053fc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::motorcycle_gz::input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motorcycle_gz/input";
  }

  static const char* value(const ::motorcycle_gz::input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motorcycle_gz::input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 force\n"
"float64 v\n"
"float64 d\n"
"float64 t\n"
;
  }

  static const char* value(const ::motorcycle_gz::input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motorcycle_gz::input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force);
      stream.next(m.v);
      stream.next(m.d);
      stream.next(m.t);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motorcycle_gz::input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motorcycle_gz::input_<ContainerAllocator>& v)
  {
    s << indent << "force: ";
    Printer<double>::stream(s, indent + "  ", v.force);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
    s << indent << "t: ";
    Printer<double>::stream(s, indent + "  ", v.t);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTORCYCLE_GZ_MESSAGE_INPUT_H
